version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: credit-flow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: credit-flow-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards/credit-flow-dashboard.json:/etc/grafana/dashboards/credit-flow-dashboard.json
    depends_on:
      - prometheus
    networks:
      - monitor

networks:
  monitor:
    driver: bridge
